openapi: 3.0.0
info:
  title: Digital Battery Passport Back Office API
  version: '0.1'
paths:
  /bo/dbp/test-data:
    post:
      tags:
        - Back Office API DBP
      summary: Insert the demo passport into MongoDB.
      responses:
        '201':
          description: registered successfully
        '401':
          description: provided API key is not valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
  /bo/dbp/:
    get:
      tags:
        - Back Office API DBP
      summary: Get a passport for Tier1 (public) access
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DigitalBatteryPassport'
        '401':
          description: provided API key is not valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
    post:
      tags:
        - Back Office API DBP
      summary: Create a Digital Battery Passport.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DigitalBatteryPassport'
      responses:
        '201':
          description: Digital Battery Passport created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateDigitalBatteryPassportResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '401':
          description: provided API key is not valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
  /bo/dbp/t2:
    get:
      tags:
        - Back Office API DBP
      summary: Get a passport for Tier2 (Legitimate Access) access
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DigitalBatteryPassport'
        '401':
          description: provided API key is not valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
  /bo/dbp/t3:
    get:
      tags:
        - Back Office API DBP
      summary: Get a passport for Tier3 (Regulator) access
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DigitalBatteryPassport'
        '401':
          description: provided API key is not valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
  /bo/dbp/t2/{resourceId}/performance:
    get:
      tags:
        - Back Office API DBP
      summary: request get the performance data of a specific battery.
      parameters:
        - name: resourceId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Performance'
        '401':
          description: provided API key is not valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
    post:
      tags:
        - Back Office API DBP
      summary: update performance data for a battery.
      parameters:
        - name: resourceId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Performance'
      responses:
        '201':
          description: Update Digital Battery Passport
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DigitalBatteryPassport'
        '401':
          description: provided API key is not valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
  /bo/dbp/t2/{resourceId}/maintenance:
    get:
      tags:
        - Back Office API DBP
      summary: request maintenance data of a specific battery.
      parameters:
        - name: resourceId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MaintenanceInformation'
        '401':
          description: provided API key is not valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
    post:
      tags:
        - Back Office API DBP
      summary: post a new maintenance event for a specific battery.
      parameters:
        - name: resourceId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MaintenanceInformationItem'
      responses:
        '201':
          description: registered successfully
        '401':
          description: provided API key is not valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
components:
  schemas:
    ApiError:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
    CreateDigitalBatteryPassportResponse:
      type: object
      required:
        - DBPId
      properties:
        DBPId:
          type: string
    MaintenanceInformationItem:
      type: object
      required:
        - eventDate
        - activityType
        - modifications
      properties:
        eventDate:
          type: string
          format: date-time
        activityType:
          type: object
          required:
            - code
            - definition
          properties:
            code:
              type: string
            definition:
              type: string
        modifications:
          type: object
          additionalProperties: true
    MaintenanceInformation:
      type: array
      items:
        $ref: '#/components/schemas/MaintenanceInformationItem'
    Performance:
      type: object
      properties:
        batteryCondition:
          type: object
        batteryTechnicalProperties:
          type: object
    DigitalBatteryPassport:
      type: object
      properties:
        materialComposition:
          type: object
        circularity:
          type: object
        supplyChainDueDiligence:
          type: object
        maintenanceInformation:
          $ref: '#/components/schemas/MaintenanceInformation'
        performance:
          $ref: '#/components/schemas/Performance'
        dynamicUpdates:
          type: array
          items:
            type: object
        carbonFootprint:
          type: object
        generalProductInformation:
          type: object
        labeling:
          type: object
